#if !defined(AFX_COMPRESSFUNCTION_H__C7BFA0E8_2108_4D0F_8328_D3B7FC480F8E__INCLUDED_)
#define AFX_COMPRESSFUNCTION_H__C7BFA0E8_2108_4D0F_8328_D3B7FC480F8E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCompressFunction wrapper class

class CCompressFunction : public COleDispatchDriver
{
public:
	CCompressFunction() {}		// Calls COleDispatchDriver default constructor
	CCompressFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCompressFunction(const CCompressFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCompress();
	void SetCompress(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_COMPRESSFUNCTION_H__C7BFA0E8_2108_4D0F_8328_D3B7FC480F8E__INCLUDED_)
