#if !defined(AFX_FULLSCREENTOOL_H__1C442733_32E1_476A_AEAB_E601604B9698__INCLUDED_)
#define AFX_FULLSCREENTOOL_H__1C442733_32E1_476A_AEAB_E601604B9698__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CFullScreenTool wrapper class

class CFullScreenTool : public COleDispatchDriver
{
public:
	CFullScreenTool() {}		// Calls COleDispatchDriver default constructor
	CFullScreenTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFullScreenTool(const CFullScreenTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetReleaseKey();
	void SetReleaseKey(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FULLSCREENTOOL_H__1C442733_32E1_476A_AEAB_E601604B9698__INCLUDED_)
