#if !defined(AFX_LEVELSEGMENT_H__23D2D87E_9BA3_4172_8EFE_A1A9DE4F29C3__INCLUDED_)
#define AFX_LEVELSEGMENT_H__23D2D87E_9BA3_4172_8EFE_A1A9DE4F29C3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePoint2D;

/////////////////////////////////////////////////////////////////////////////
// CLevelSegment wrapper class

class CLevelSegment : public COleDispatchDriver
{
public:
	CLevelSegment() {}		// Calls COleDispatchDriver default constructor
	CLevelSegment(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLevelSegment(const CLevelSegment& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetNumPoints();
	CTeePoint2D GetPoints(long Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LEVELSEGMENT_H__23D2D87E_9BA3_4172_8EFE_A1A9DE4F29C3__INCLUDED_)
