#if !defined(AFX_ORGITEMCOLLECTION_H__57600BD4_96C8_40D6_8595_0F4906C07232__INCLUDED_)
#define AFX_ORGITEMCOLLECTION_H__57600BD4_96C8_40D6_8595_0F4906C07232__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COrgItem;

/////////////////////////////////////////////////////////////////////////////
// COrgItemCollection wrapper class

class COrgItemCollection : public COleDispatchDriver
{
public:
	COrgItemCollection() {}		// Calls COleDispatchDriver default constructor
	COrgItemCollection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	COrgItemCollection(const COrgItemCollection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	COrgItem GetItems(long Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ORGITEMCOLLECTION_H__57600BD4_96C8_40D6_8595_0F4906C07232__INCLUDED_)
