#if !defined(AFX_ORGSERIES_H__E6811BBA_1F52_4A64_84AA_BD1A41933BD5__INCLUDED_)
#define AFX_ORGSERIES_H__E6811BBA_1F52_4A64_84AA_BD1A41933BD5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COrgItem;
class COrgShape;
class COrgItemCollection;
class CSpacing;

/////////////////////////////////////////////////////////////////////////////
// COrgSeries wrapper class

class COrgSeries : public COleDispatchDriver
{
public:
	COrgSeries() {}		// Calls COleDispatchDriver default constructor
	COrgSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	COrgSeries(const COrgSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long Add(LPCTSTR Text, long Superior);
	long FirstChild(long ValueIndex);
	// method 'GetBounds' not emitted because of invalid return type or parameter type
	COrgItem GetItem(long Index);
	COrgShape GetFormat();
	COrgItemCollection GetItems();
	long GetLineStyle();
	void SetLineStyle(long nNewValue);
	CSpacing GetSpacing();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ORGSERIES_H__E6811BBA_1F52_4A64_84AA_BD1A41933BD5__INCLUDED_)
