#if !defined(AFX_SOFTENFILTER_H__607EAE30_0E0A_43B7_A105_D37A731E0870__INCLUDED_)
#define AFX_SOFTENFILTER_H__607EAE30_0E0A_43B7_A105_D37A731E0870__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSoftenFilter wrapper class

class CSoftenFilter : public COleDispatchDriver
{
public:
	CSoftenFilter() {}		// Calls COleDispatchDriver default constructor
	CSoftenFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSoftenFilter(const CSoftenFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SOFTENFILTER_H__607EAE30_0E0A_43B7_A105_D37A731E0870__INCLUDED_)
