#if !defined(AFX_VIDEOPLAYERTOOL_H__2D4B0E6E_633B_4567_8E97_FE4677CA143E__INCLUDED_)
#define AFX_VIDEOPLAYERTOOL_H__2D4B0E6E_633B_4567_8E97_FE4677CA143E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePicture;
class CFilterItems;

/////////////////////////////////////////////////////////////////////////////
// CVideoPlayerTool wrapper class

class CVideoPlayerTool : public COleDispatchDriver
{
public:
	CVideoPlayerTool() {}		// Calls COleDispatchDriver default constructor
	CVideoPlayerTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVideoPlayerTool(const CVideoPlayerTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetPaused();
	CTeePicture GetImage();
	BOOL GetPlaying();
	long GetPosition();
	void SetPosition(long nNewValue);
	long GetStartFrame();
	long GetEndFrame();
	long GetDelay();
	void SetDelay(long nNewValue);
	CString GetFileName();
	void SetFileName(LPCTSTR lpszNewValue);
	BOOL GetLoop();
	void SetLoop(BOOL bNewValue);
	CFilterItems GetFilters();
	void Pause();
	void Play();
	void Stop();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VIDEOPLAYERTOOL_H__2D4B0E6E_633B_4567_8E97_FE4677CA143E__INCLUDED_)
