#if !defined(AFX_ZOOMFILTER_H__BEFD26DD_D1B3_4478_8FBE_27811F341BDB__INCLUDED_)
#define AFX_ZOOMFILTER_H__BEFD26DD_D1B3_4478_8FBE_27811F341BDB__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CZoomFilter wrapper class

class CZoomFilter : public COleDispatchDriver
{
public:
	CZoomFilter() {}		// Calls COleDispatchDriver default constructor
	CZoomFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CZoomFilter(const CZoomFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetPercent();
	void SetPercent(double newValue);
	BOOL GetSmooth();
	void SetSmooth(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ZOOMFILTER_H__BEFD26DD_D1B3_4478_8FBE_27811F341BDB__INCLUDED_)
